[package]
name = "day3"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.2"
rstest = "0.26.1"
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
